# ----------------------------------------------------------------------------
# Copyright © 2025, Spyder Bot
#
# Licensed under the terms of the Not open source
# ----------------------------------------------------------------------------

commit_message: '[ci skip] New %language% translation from Crowdin'
append_commit_message: false
files:
  - source: /eda_explorer/spyder/locale/eda_explorer.pot
    translation: /eda_explorer/eda_explorer/locale/%two_letters_code%/LC_MESSAGES/%file_name%.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        zh-CN: zh_CN
